package com.capstone.hidroqu.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.lerp

val primaryLight = Color(0xFF086B5A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFA1F2DD)
val onPrimaryContainerLight = Color(0xFF00201A)
val secondaryLight = Color(0xFF006970)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF9DF0F8)
val onSecondaryContainerLight = Color(0xFF002022)
val tertiaryLight = Color(0xFF6A5F11)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF4E489)
val onTertiaryContainerLight = Color(0xFF201C00)
val errorLight = Color(0xFF904A49)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD8)
val onErrorContainerLight = Color(0xFF3B080B)
val onBackgroundLight = Color(0xFF171D1B)
val surfaceLight = Color(0xFFF5FAFB)
val onSurfaceLight = Color(0xFF171D1E)
val surfaceVariantLight = Color(0xFFDBE5E0)
val onSurfaceVariantLight = Color(0xFF3F4946)
val outlineLight = Color(0xFF6F7975)
val outlineVariantLight = Color(0xFFBFC9C4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3133)
val inverseOnSurfaceLight = Color(0xFFECF2F3)
val inversePrimaryLight = Color(0xFF85D6C1)
val surfaceDimLight = Color(0xFFD5DBDC)
val surfaceBrightLight = Color(0xFFF5FAFB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F6)
val surfaceContainerLight = Color(0xFFE9EFF0)
val surfaceContainerHighLight = Color(0xFFE3E9EA)
val surfaceContainerHighestLight = Color(0xFFDEE3E5)
val backgroundLight = lerp(surfaceLight, primaryLight, 0.08f)

// Dark theme colors
val primaryDark = Color(0xFF85D6C1)
val onPrimaryDark = Color(0xFF00382E)
val primaryContainerDark = Color(0xFF005143)
val onPrimaryContainerDark = Color(0xFFA1F2DD)
val secondaryDark = Color(0xFF80D4DC)
val onSecondaryDark = Color(0xFF00363B)
val secondaryContainerDark = Color(0xFF004F55)
val onSecondaryContainerDark = Color(0xFF9DF0F8)
val tertiaryDark = Color(0xFFD7C770)
val onTertiaryDark = Color(0xFF383000)
val tertiaryContainerDark = Color(0xFF514700)
val onTertiaryContainerDark = Color(0xFFF4E489)
val errorDark = Color(0xFFFFB3B1)
val onErrorDark = Color(0xFF571D1E)
val errorContainerDark = Color(0xFF733333)
val onErrorContainerDark = Color(0xFFFFDAD8)
val onBackgroundDark = Color(0xFFDEE4E0)
val surfaceDark = Color(0xFF0E1415)
val onSurfaceDark = Color(0xFFDEE3E5)
val surfaceVariantDark = Color(0xFF3F4946)
val onSurfaceVariantDark = Color(0xFFBFC9C4)
val outlineDark = Color(0xFF89938F)
val outlineVariantDark = Color(0xFF3F4946)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE3E5)
val inverseOnSurfaceDark = Color(0xFF2B3133)
val inversePrimaryDark = Color(0xFF086B5A)
val surfaceDimDark = Color(0xFF0E1415)
val surfaceBrightDark = Color(0xFF343A3B)
val surfaceContainerLowestDark = Color(0xFF090F10)
val surfaceContainerLowDark = Color(0xFF171D1E)
val surfaceContainerDark = Color(0xFF1B2122)
val surfaceContainerHighDark = Color(0xFF252B2C)
val surfaceContainerHighestDark = Color(0xFF303637)
val backgroundDark = lerp(surfaceDark, primaryDark, 0.08f)